theme: jekyll-theme-minimal
title: Paul Guermonprez
description: Innovation Engineer with a focus on AI and CyberSecurity
markdown: kramdown

author:
  name: Paul Guermonprez
  email: paul@guermonprez.eu
  github: guermonprez
  
  avatar: https://github.com/guermonprez/guermonprez.github.io/blob/master/id.jpg?raw=true
  location: San Francisco
