theme: jekyll-theme-slate
title: Paul Guermonprez
logo: https://github.com/guermonprez/guermonprez.github.io/blob/master/id.jpg?raw=true
show_downloads: false

author:
  name: Paul Guermonprez
  email: paul@guermonprez.eu
  github: guermonprez
  
  avatar: https://github.com/guermonprez/guermonprez.github.io/blob/master/id.jpg?raw=true
  location: San Francisco
